"""Bone X-rays — deterministic invariants of cb_zinets' generated structure.

Every test here began life as an ad-hoc audit during a real incident or
migration (2026-07-04: zn_zi_part whitespace, thin-book conversion, 405-book
repair, baked-TOC strip). The armature principle says structure is QA'd by
assertion, content by review — this file is the assertion half. Run:

    python3 -m pytest tests/ -q

All tests are read-only against public/ and db/ (safe during batch runs),
except the catalog concurrency test, which uses a scratch file.
"""
import json
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from cb_paths import book_rel, concept_rel, parse_variant  # noqa: E402
import catalog_lib  # noqa: E402

DOMAINS = ROOT / "public" / "domains"
CONCEPTS = ROOT / "public" / "concepts"
DB = ROOT / "db" / "cb_zinets.sqlite"

_PART_COLS = [
    "zi_left_up", "zi_left", "zi_left_down", "zi_up", "zi_mid", "zi_down",
    "zi_right_up", "zi_right", "zi_right_down", "zi_mid_out", "zi_mid_in",
]


def _is_single_cjk(s: str) -> bool:
    return len(s) == 1 and (
        0x4E00 <= ord(s) <= 0x9FFF or 0x3400 <= ord(s) <= 0x4DBF
        or 0x20000 <= ord(s) <= 0x2A6DF
    )


def _books():
    return sorted(DOMAINS.glob("*/output/*/*/html/book_*.html"))


# ── Path schema ───────────────────────────────────────────────────────────────

def test_paths_roundtrip():
    rel = book_rel("intro", "zh", "sonnet", "phrase_衣食住行")
    v = parse_variant(rel)
    assert v == {"level": "intro", "language": "zh", "model": "sonnet",
                 "kind": "book", "name": "phrase_衣食住行"}
    v2 = parse_variant(concept_rel("core", "en", "gemma4", "思"))
    assert (v2["kind"], v2["name"]) == ("concept", "思")
    assert parse_variant("output/intro.en/html/book_x.html") is None  # legacy


def test_paths_js_twin_agrees():
    """cb_paths.py and src/lib/paths.js must encode the same schema."""
    script = (
        "const p = await import('" + str(ROOT / "src/lib/paths.js") + "');"
        "const v = p.parseVariant(p.bookRel('intro','zh','sonnet','phrase_X'));"
        "console.log(JSON.stringify(v));"
    )
    out = subprocess.run(["node", "--input-type=module", "-e", script],
                         capture_output=True, text=True)
    assert out.returncode == 0, out.stderr
    assert json.loads(out.stdout) == {
        "level": "intro", "language": "zh", "model": "sonnet",
        "kind": "book", "name": "phrase_X",
    }


# ── Decomposition data (zn_zi_part) ──────────────────────────────────────────

def test_no_padded_decomposition_cells():
    conn = sqlite3.connect(DB)
    union = " UNION ALL ".join(f"SELECT {c} AS p FROM zn_zi_part" for c in _PART_COLS)
    n = conn.execute(
        f"SELECT count(*) FROM ({union}) WHERE p IS NOT NULL AND p != '' AND p != trim(p)"
    ).fetchone()[0]
    conn.close()
    assert n == 0, f"{n} whitespace-padded cells in zn_zi_part (see docs/TEST/README-zinets-data-quality.md)"


def test_decomposition_recurses_through_trimmed_parts():
    """惛 → 忄 + 昏, and 昏 must keep decomposing (氏, 日) — the padded-cell
    bug silently truncated this chain."""
    from phrase_decomposer import decompose_character
    conn = sqlite3.connect(DB)
    d = decompose_character("惛", conn, 10)
    conn.close()
    assert {"氏", "日"} <= set(d), f"recursion truncated: {d}"


# ── Generated pages ───────────────────────────────────────────────────────────

def test_no_padded_page_names():
    bad = [p.name for p in CONCEPTS.rglob("concept_*.html")
           if (n := p.stem[len("concept_"):]) != n.strip()]
    assert not bad, f"whitespace-padded canonical filenames: {bad[:5]}"


def test_canonical_pages_are_navless_with_marker():
    """Canonicals are shared across domains: no baked sidebar TOC (it would
    name the birth domain), but the spl-credit existence marker must stay."""
    with_nav, no_marker = [], []
    for p in CONCEPTS.rglob("concept_*.html"):
        if p.is_symlink():
            continue
        t = p.read_text(encoding="utf-8", errors="ignore")
        if '<nav class="toc"' in t:
            with_nav.append(p)
        if "spl-credit" not in t and "Generated by" not in t:
            no_marker.append(p)
    assert not with_nav, f"{len(with_nav)} canonicals still carry a baked TOC, e.g. {with_nav[:3]}"
    assert not no_marker, f"{len(no_marker)} canonicals lack the existence marker, e.g. {no_marker[:3]}"


def test_book_invariants():
    """Thin-book structure: nav TOC + <main> + h1 + credit; every TOC concept
    link resolves; no inlined single-CJK section whose page exists; no repair
    fragments (the 2026-07-04 offset-bug signature)."""
    problems = []
    for b in _books():
        t = b.read_text(encoding="utf-8", errors="ignore")
        rel = b.relative_to(DOMAINS)
        if "<main>" not in t:
            problems.append(f"{rel}: no <main>")
            continue
        if not re.search(r'<main>\s*<h1 class="book-title">[^<]*</h1>', t):
            problems.append(f"{rel}: missing/clipped h1")
        if '"ref="' in t:
            problems.append(f"{rel}: fused fragment")
        nav = re.search(r'<nav class="toc">.*?(?:</nav>|<main>)', t, re.S)
        if not nav:
            problems.append(f"{rel}: no nav TOC")
            continue
        for href in re.findall(r'href="(concept_[^"]+)"', nav.group(0)):
            if not (b.parent / href).exists():
                problems.append(f"{rel}: dead TOC link {href}")
                break
        for sid in re.findall(r'<section id="([^"]+)">', t):
            if _is_single_cjk(sid) and (b.parent / f"concept_{sid}.html").exists():
                problems.append(f"{rel}: unthinned inline section {sid}")
                break
    assert not problems, f"{len(problems)} book problems, e.g. {problems[:5]}"


def test_domain_concept_symlinks_resolve():
    broken = [p for p in DOMAINS.glob("*/output/*/*/html/concept_*.html")
              if p.is_symlink() and not p.exists()]
    assert not broken, f"{len(broken)} broken symlinks, e.g. {broken[:3]}"


# ── Domain builder (single materialization path) ─────────────────────────────

def test_phrase_graph_dict_wires_deep_edges():
    """The consolidated builder must include sub-component concepts with their
    own composed_of — the pre-P2 CLI drift dropped those edges in graph.html
    (e.g. 春生夏长: 戕→臧 missing while graph.yaml implied it)."""
    from domain_builder import build_phrase_graph_dict
    conn = sqlite3.connect(DB)
    gd = build_phrase_graph_dict("卧虎藏龙", "phrase_卧虎藏龙", conn)
    conn.close()
    assert "phrase_卧虎藏龙" in gd["applications"]
    assert gd["applications"]["phrase_卧虎藏龙"]["needs"] == ["卧", "虎", "藏", "龙"]
    deep_concepts = [z for z, n in gd["concepts"].items()
                     if z not in "卧虎藏龙" and n.get("composed_of")]
    assert deep_concepts, "no intermediate concept carries composed_of — deep edges lost"


# ── Catalog ───────────────────────────────────────────────────────────────────

def test_catalog_concepts_carry_pinyin():
    """Home's Concepts search matches on generated_concepts[].pinyin — every
    entry whose name is mappable must carry it. Writers that rebuild these
    entries without pinyin_lib.concept_pinyin_fields blind the search
    (2026-07-04: batch rescan wiped 8,542 entries; typing 'bu' found no
    concepts). Repair: python3 scripts/backfill_pinyin.py."""
    from pinyin_lib import load_pinyin_map, concept_pinyin_fields
    pinyin_map = load_pinyin_map(DB)
    missing = []
    for d in catalog_lib.read_catalog():
        for c in d.get("generated_concepts", []):
            expected = concept_pinyin_fields(c.get("name", ""), pinyin_map)
            if expected and not c.get("pinyin"):
                missing.append((d["id"], c["name"]))
    assert not missing, f"{len(missing)} concept entries lack pinyin, e.g. {missing[:5]}"


def test_catalog_is_valid():
    catalog = catalog_lib.read_catalog()
    ids = [d["id"] for d in catalog]
    assert len(ids) == len(set(ids)), "duplicate domain ids"
    for d in catalog:
        for c in d.get("generated_concepts", []):
            assert c["name"] == c["name"].strip(), f"padded concept name in {d['id']}: {c['name']!r}"
        seen = set()
        for b in d.get("books", []):
            key = (b["target"], b.get("model"), b["file"])
            assert key not in seen, f"duplicate book entry in {d['id']}: {key}"
            seen.add(key)


def test_catalog_concurrent_writers_lose_nothing(tmp_path):
    """8 processes × 25 locked updates → exactly 200 entries."""
    import multiprocessing as mp
    scratch = tmp_path / "catalog.json"
    scratch.write_text("[]")
    ctx = mp.get_context("spawn")
    with ctx.Pool(8) as pool:
        pool.starmap(_hammer, [(str(scratch), i) for i in range(8)])
    assert len(json.loads(scratch.read_text())) == 200


def _hammer(path: str, i: int) -> None:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    import catalog_lib as cl
    for j in range(25):
        cl.update_catalog(lambda c: c.append({"id": f"{i}-{j}"}), Path(path))


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-q"]))
