#!/usr/bin/env python3
"""Strip the baked sidebar TOC from canonical concept pages (P5 in
docs/DEV/readme-retro-armature.md).

Canonical pages under public/concepts/ are shared across domains via
symlinks, but each carried a <nav class="toc"> naming its *birth* domain —
the source of the cross-domain TOC defects (Book sidebar hijack, Graph
detail pane showing the wrong phrase). Navigation is the viewer's job;
spl/tools.py:write_concept_html now emits navless pages
(_CONCEPT_PAGE_TEMPLATE), and this script brings existing pages in line:

  - remove the <nav class="toc">…</nav> block
  - collapse the .page grid to single column
  - drop the birth-domain from <title>
  - append the credit footer after </main> (existence-check marker)

Idempotent; --dry-run to preview. Books are untouched (their TOC is theirs).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CONCEPTS_DIR = ROOT / "public" / "concepts"

NAV_RE = re.compile(r'[ \t]*<nav class="toc">.*?</nav>\n?', re.S)
GRID_CSS = '.page{display:grid;grid-template-columns:260px 1fr;min-height:100vh}'
FOOTER = ('  <div class="spl-credit" style="padding:14px 64px;font-size:11px;'
          'color:#9aa3ad;font-family:system-ui,sans-serif">Generated by '
          '<a href="https://github.com/digital-duck/SPL.py" target="_blank" '
          'style="color:#7a8794">SPL</a></div>\n')


def strip_page(text: str) -> str | None:
    """Return converted page, or None if it has no baked nav (already done)."""
    new, n = NAV_RE.subn('', text)
    if n == 0:
        return None
    new = new.replace(GRID_CSS, '.page{min-height:100vh}')
    new = re.sub(r'<title>([^<]*?) — [^<]*</title>', r'<title>\1</title>', new, count=1)
    if 'spl-credit' not in new.split('</main>', 1)[-1]:
        new = new.replace('</main>\n', '</main>\n' + FOOTER, 1)
    return new


def main():
    dry_run = '--dry-run' in sys.argv
    done = skipped = no_main = 0
    for page in sorted(CONCEPTS_DIR.rglob('concept_*.html')):
        if page.is_symlink():
            continue
        text = page.read_text(encoding='utf-8')
        new = strip_page(text)
        if new is None:
            skipped += 1
            continue
        if '</main>' not in new:
            no_main += 1
            print(f'  !! no </main>, left untouched: {page.relative_to(ROOT)}')
            continue
        done += 1
        if not dry_run:
            page.write_text(new, encoding='utf-8')
    mode = 'DRY RUN — no files written' if dry_run else 'done'
    print(f'Strip baked TOC ({mode}): {done} converted, {skipped} already navless, {no_main} anomalies')


if __name__ == '__main__':
    main()
