import { Header } from '../components/Header.js'

export function About(container) {
  container.innerHTML = ''
  container.appendChild(Header())

  const main = document.createElement('main')
  main.className = 'cb-about'
  main.innerHTML = `
    <h1>About ZiNets ConceptBook</h1>
    <p>
      <strong>ZiNets ConceptBook</strong> is the concept-book layer of the
      <a href="https://github.com/digital-duck/zinets_vis" target="_blank" rel="noopener">ZiNets portal</a>.
      It maps all 6,000+ Chinese characters onto a directed acyclic graph whose
      nodes are characters (primitive, concept, application) and whose edges
      are decomposition relationships.
    </p>

    <h2>The LEGO principle</h2>
    <p>
      ~422 elemental primitives — including the 214 KangXi radicals and additional
      semantically important pieces — are the bricks. Every other character snaps
      together from them. <code>graph_lib.reducible()</code> machine-checks this
      claim: every character must trace back to the primitive set.
    </p>

    <h2>Phono-semantic compounds (形声字)</h2>
    <p>
      Over 80% of Chinese characters follow one rule: one piece gives the
      <em>meaning</em> (形), another gives the <em>sound</em> (声). Master
      ~200 bricks and this single principle, and thousands of unseen characters
      become decodable on sight.
    </p>

    <h2>HSK tiers</h2>
    <p>
      Characters are grouped by HSK set (<code>set_id</code>) so learners can
      start with the most common 300 characters and expand progressively.
    </p>

    <h2>Data source</h2>
    <p>
      The character graph is generated from the ZiNets SQLite database
      (<code>zinets_cache.sqlite</code>) by <code>scripts/zinets_to_graph.py</code>.
      Concept books are generated by
      <a href="https://github.com/digital-duck/SPL.py" target="_blank" rel="noopener">SPL.py</a>.
    </p>

    <h2>Open source</h2>
    <p>
      Source at
      <a href="https://github.com/digital-duck/cb_zinets" target="_blank" rel="noopener">github.com/digital-duck/cb_zinets</a>.
      MIT licence.
    </p>
  `
  container.appendChild(main)
}
